scripts: Makefile.lib: Don't disable dtc checks
* Somehow, they doesn't exist on aosp dtc, causing build errors like this:
FATAL ERROR: Unrecognized check name "avoid_unnecessary_addr_size"